import "./App.css";
// import useCounterStore from "./stores/useCounterStore";
import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { Typography } from "@mui/material";
import AppDescription from "./components/AppDescription";
import AnalysisForm from "./components/AnalysisForm";

function App() {
  return (
    <div className="App">
      <AppDescription />
      <div className="card"></div>
      <AnalysisForm />
      <Typography variant="caption">
        P.S. The text on this page was generated by the ChatGPT language model
      </Typography>
    </div>
  );
}

export default App;
